unittests-script: ../../test_scripts/run_unittests_python.sh
conformance-tests-script: ../../test_scripts/run_conformance_tests_python.sh
v: true  # verbose flag, defaults to false if not set
debug: true  # debug flag, defaults to false if not set
api: http://127.0.0.1:5000