system_requirements:
  timeout:
    command: timeout
    error_message: |
      Error: Required system command 'timeout' is not available.
      This command is needed to enforce time limits on test execution.

      To install the timeout command:
      - On Linux: Install coreutils package
        - Debian/Ubuntu: sudo apt-get install coreutils
        - CentOS/RHEL: sudo yum install coreutils
        - Fedora: sudo dnf install coreutils
      - On macOS:
        - Using Homebrew: brew install coreutils
        - Using MacPorts: port install coreutils
      - On Windows: Use Windows Subsystem for Linux (WSL), Cygwin, or Git Bash

error_messages:
  template_not_found:
    message: |
      The required template could not be found. Templates are searched in the following order (highest to lowest precedence):

        1. The directory containing your .plain file
        2. The directory specified by --template-dir (if provided)
        3. The built-in 'standard_template_library' directory

      Please ensure that the missing template exists in one of these locations, or specify the correct --template-dir if using custom templates.
